### PR TITLE
Add data import from data.statistik.gv.at

### PR DESCRIPTION
**Pull request by bernhard-da**
work-in-progress: add od-functionality

### CODE REVIEW

**Comment by GregorDeCillia** [comment]
Thank you very much for this contribution!

As discussed behind our firewall, I have already tested this and the new `od_table` class is almost perfectly interchangable with the existing `sc_table` class. 

I'll make some finetunings in the next couple of days and hopefully, I'll be able to adress these points

- [ ] Format categorical columns as `factor`. This is necessary for `STATgraph::sg_timeseries()` which uses `levels()`. Currently, the parameter `color` does not work with `sg_timeseries()`
- [ ] Use a format in `$field(i)$parsed` which is consistent with `sc_table`:  `<date>` for time variables and `<fct>` for categorical variables
- [ ] The timings only measure the download time for the datasets, not for the metadata
- [x] Unnecessary traffic in `od_table$initialize()?` It's probably more efficent to test for a `404` response.
- [ ] Inline TODO https://github.com/statistikat/STATcubeR/blob/ecc01ac941eac996d00912b1369bfe575263c4c2/R/od_utils.R#L98
- [x] Set aggregation-function in `$meta$measures$fun` to `NA`
- [ ] For the population-forecasts until 2101, the time variable is not recognized. This has to be fixed in https://github.com/statistikat/STATcubeR/blob/ecc01ac941eac996d00912b1369bfe575263c4c2/R/table_field.R#L24 Example: **OGD_bevstprogjdgebland_PR_BEVJDGB_4** (Bevölkerung zum Jahresanfang nach dem Geburtsland 2016 bis 2101).
- [ ] Move the rendering-logic in `$render()` to `STATgraphGUI`

**Comment by bernhard-da** [comment]
@GregorDeCillia the issue with incorrect timings is already fixed.

**Comment by GregorDeCillia** [comment]
@bernhard-da thanks. I think the other TODOs should also be pretty straightforward to complete.

**Comment by GregorDeCillia** [comment]
- [ ] `parse_time` and `round` are currently ignored in `od_tabulate()` https://github.com/statistikat/STATcubeR/blob/3257bd10b71a49ae3333d467d8310f98bfb756d6/R/od_tabulate.R#L38
    - For `round` this makes sense, since there is no metadata to provide a precision
    - For `parse_time` this is relevant in case the original labels of the months/quarters/years are required 
- [ ] Translate error messages to english. Example https://github.com/statistikat/STATcubeR/blob/merge-od/R/od_utils.R#L19

**Comment by GregorDeCillia** [comment]
I just made some major changes to the import logic in 1179486. The returned object now only contains three columns in `$meta$measures` since `fun` and `annotations` are not applicable for this class. It also enables caching, see the commit message.

Now the question is how to deal with aggregation of data. The way I see it, there are two types of datasets

* Datasets that only contain measures which can be aggregated using unweighted sums. Those generally do not contain total-codes and can/must be aggregated directly using `base::sum()`
* Datasets such as `OGD_veste309_Veste309_1`, where certain measures can not be aggregated directly. Those seem to always contain total codes for all fields except time variables

**My suggestion**: Since it is basically impossible to automatically detect total codes, I'd suggest `od_tabulate()` aggregates directly by default. If a user wants to use total codes for aggregation, those have to be supplied as characters. For example

```r
x <- od_table("OGD_veste309_Veste309_1")
x$tabulate(
  total_codes = list(
    `C-A11-0` = "A11-1", `
    `C-STAATS-0` = "STAATS-9", 
    `C-VEBDL-0` = "VEBDL10", 
    `C-BESCHV-0` = "BESCHV-1"
  )
)
```

**Comment by GregorDeCillia** [comment]
About `rvest -> xml2`. The package `xml2` is already required for `httr::content()` in `od_list()` https://github.com/statistikat/STATcubeR/blob/ce5af0fea1f7443c38891af6ad650904e3443836/R/od_list.R#L23
see `?httr::content` or follow the rabbit hole

```
httr::content() -> httr:::parse_auto() -> httr:::parsers$`text/html`()
```

Other calls to `httr::content()` always use the json parser which is implemented in the `jsonlite` package

**Comment by GregorDeCillia** [comment]
With 20a1ab7, the `od_table` class should be feature-complete for our internal needs. Anyone interested in trying can do so with 

```
remotes::install_github("STATistikat/STATcubeR", "20a1ab7")
library(STATcubeR)
## start with the examples from the documentation
?od_table
?od_tabulate
```

I'm going to leave this PR open for a little while to see if any further extensions come up when integrating this class. Possible improvements

- [ ] Documentation
    - [ ] Write a pkgdown-vignette and put it on https://statistikat.github.io/STATcubeR/
    - [ ] Mention OGD import in README and the repo-description
- [ ] `od_tabulate()`
    - [ ] Special handling of time variables: Don't aggregate them unless a specific flag is set
    - [ ] Sort rows/columns before returning. Currently, the column order is not necessarily the same as in `$data` if aggregation is done via `rowsum()`. Rows could be indexed lexicographically by all fields.
    - [ ] Recode zeros? I don't think this makes sense because zeros should not be interpreted as `NA` for OGD but this needs to be clarified with the OGD support team.
 - [ ] If `{dataset_id}_HEADER.csv` contains any columns other than `"code"`, `"name"` and `"name_en"`, these additional columns are not included in the `od_table` object. The same is true for additional columns in `{dataset_id}_{field_id}.csv`. Maybe append them to `$meta$fields` and `$field(i)`.
 - [ ] Allow partial matching of codes and labels in `$fields()` and `$total_codes()` the same way `...` is treated in `od_tabulate()`

```r
table <- od_table("OGD_veste309_Veste309_1")
x$field("Sex")                         # return the same value as in `table$field(2)`
x$total_codes(Citizenship = "Total")   # treat as table$total_codes(`C-STAATS-0` = "STAATS-9")
```

**Comment by GregorDeCillia** [comment]
I just added a development version of the pkgdown ite under https://statistikat.github.io/STATcubeR/dev/. It contains four new articles about `do_table()` and friends. 

* [overview](https://statistikat.github.io/STATcubeR/dev/articles/od_table.html)
* [tabulation](https://statistikat.github.io/STATcubeR/dev/articles/od_tabulate.html)
* [caching](https://statistikat.github.io/STATcubeR/dev/articles/od_resources.html)
* [available datasets](https://statistikat.github.io/STATcubeR/dev/articles/od_list.html)

Not all features documented there are part of the VCS yet, but this is the direction it is going.

**Comment by GregorDeCillia** [comment]
`OGD_gest_kalwo_alter_GEST_KALWOCHE_5J_100` uses calender weeks for the time variable, which is not compatible with the time parsing algorithm. The issue here is that the week numbers are interpreted as month numbers. 

```r
x <- od_table("OGD_gest_kalwo_alter_GEST_KALWOCHE_5J_100")
x$raw$extras$metadata_modified
#> [1] "2021-07-22T09:02:59"
x$meta$fields[, c(1, 3, 4)]
#>   code         label_en                           nitems
#>   <chr>        <chr>                               <int>
#> 1 C-KALWOCHE-0 Calendar week                        1121
#> 2 C-B00-0      Province (NUTS 2 unit) of deceased      9
#> 3 C-ALTER5-0   5 years age group of deceased          20
#> 4 C-C11-0      Gender of deceased                      2
x$field("Calendar week")[10:14, c(1, 3, 4)]
#>   code        label_en                                                  parsed    
#>   <chr>       <chr>                                                     <date>    
#> 1 KALW-200010 10. Calendar week 2000 (week from 6.3.2000 to 12.3.2000)  2000-10-01
#> 2 KALW-200011 11. Calendar week 2000 (week from 13.3.2000 to 19.3.2000) 2000-11-01
#> 3 KALW-200012 12. Calendar week 2000 (week from 20.3.2000 to 26.3.2000) 2000-12-01
#> 4 KALW-200013 13. Calendar week 2000 (week from 27.3.2000 to 2.4.2000)  NA        
#> 5 KALW-200014 14. Calendar week 2000 (week from 3.4.2000 to 9.4.2000)   NA        
```

**Comment by GregorDeCillia** [comment]
TODO: define a common interface for the new `od_table` class and  `sc_table`. The most straightforward way to implement this is to use R6 class inheritance

```r
## new base class
sc_data_class <- R6::R6Class(
  # ...
)

## invoked by factory function sc_table()
sc_table_class <- R6::R6Class(
  inherits = sc_data_class,
  # ...
)

## invoked by factory function od_table()
od_table_class <- R6::R6Class(
  inherits = sc_data_class,
  # ...
)
```

- [ ] Also add a way to convert `data.frame` objects into objects of class `sg_data`
- [ ] Try not to introduce breaking changes in `sc_table`
- [ ] Apply labeling in the base class
- [ ] Make the base class mutable to allow some recoding
    - [ ] Rename measures and fields
    - [ ] Rename factor levels
    - [ ] Reorder factor levels
    - [ ] Define total codes

The recoding and `data.frame` support are needed for internal purposes, but might not be particularly useful for external users. I'd still implement them in `STATcubeR` to keep all the data import and data wrangling logic in one place. What do you think @bernhard-da ?

**Comment by bernhard-da** [comment]
@GregorDeCillia yes, i think it is good if all data-wrangling stuff is kept in `statCubeR`; 

also, the proposed solution with the two table-classes looks reasonable; 
for the editor-feature: i would suggest to implement this in a very simple way by storing key-value pairs (old, new) as lists/data.frames in private slots in the `sc_data_class` for the separate parts (rename, reorder,...). the required set/update methods will only update this (non-accessable) slots; finally we have a single `$modified_data` method that returns a data object that  including all modifications?

**Comment by GregorDeCillia** [comment]
The idea of a single access to the modified data doesn't quite work. We need to apply the recodings to the return value of `$tabulate()`. What we could do is to add a parameter `apply_recodes` to `$tabulate()`.

It is also important that all the recodes are accessible for the client code because they are needed to initialize the data-editor module to reload previous editing operations based on the database. We could add separate recode-columns to `$meta` and `$field(i)` which is a bit messy but this could be metagated with special print methods that omit these "internal" columns.

Example

```r
x$meta$field(1)
```

code | name | name_recoded | order | color
----- | ------ | ---------------| ------- | ----
M | Male | Masculine | 2 | blue
F | Female | Feminine | 1 | red

The last three columns would define the recodes. In this case, Females would always appear first in tables and graphs and plots would use a customized color palette.

```r
## custom print method
print.sc_field <- function(x) {
  x[, 1:2]
}
```

**Comment by GregorDeCillia** [comment]
My original design was to make the `STATcubeR` objects immutable and add a layer of "mutability" in another package. We could also do something along these lines with a decorator class.

```r
x <- od_table()
class(x)
#> "od_table" "sc_data" "R6"
y <- sc_mutable(x)
class(y)
#> "sc_mutable" "sc_data" "R6"
```

`y` contains a pointer to `x` , inherits from `sc_table` and adds mutability as a decorator. This means that all the `set_recodes()` type of methods are only available in the `sc_mutable` class and the "recode state" is stored there.

**Comment by bernhard-da** [comment]
@GregorDeCillia  i like the idea of the `apply_recode` parameter in the `$tabulate()` methods; but I have  question to your example from https://github.com/statistikat/STATcubeR/pull/11#issuecomment-892668962

> The last three columns would define the recodes. In this case, Females would always appear first in tables and graphs. Plots would use the colors from the last column. `label_recoded` will appear in legends and tooltips.

but I guess you meant in your example the values from the `label_recoded` column (if different from the original labels) would also appear in the plots (and not only for tooltips, ...)? 

so you suggest to create that the plot-methods (highcharter) later are based on `sc_mutable` objects (as those contain possible recodes), correct? If so, that sounds good to me! :+1:

**Comment by GregorDeCillia** [comment]
The last two commits contain a definition for the "immutable" base class. Strictly speaking, it is mutable because total codes can be defined but other than that `sc_data` does not support any recoding operations.

**Comment by GregorDeCillia** [comment]
Breaking changes

* in `sc_data`: `$data_raw` has been renamed to `$data` and the old verison of `$data` is only available through `$tabulate` now
* `od_table()$raw` was renamed to `od_table()$json`
* `sc_data()$meta$database` was renamed to `sc_data()$meta$source`

**Comment by GregorDeCillia** [comment]
A new version of the pkgdown site is available at https://statistikat.github.io/STATcubeR/dev/

This now includes a roxygen2 documentation of the three main R6 classes
* [`sc_data`](https://statistikat.github.io/STATcubeR/dev/reference/sc_data.html)
* [`sc_table_class`](https://statistikat.github.io/STATcubeR/dev/reference/sc_table_class.html)
* [`od_table_class`](https://statistikat.github.io/STATcubeR/dev/reference/od_table_class.html)

The class documentation is supplemental to the documentation of the constructor methods
* [`od_table()`](https://statistikat.github.io/STATcubeR/dev/reference/od_table.html)
* [`sc_table()` and friends](https://statistikat.github.io/STATcubeR/dev/reference/sc_table.html)

The new page also includes an [article index](https://statistikat.github.io/STATcubeR/dev/articles/index.html) and only the most important articles are directly linked from the navbar

Updates for all pkgdown related source files will be added in a separate branch because I cannot test the REST API documentation in my current development environment and need to transfer it to another server.

**Pull request merged**
