### PR TITLE
documentation updates

### PR DESCRIPTION
**Pull request by GregorDeCillia**
## WIP. do not merge yet.
 
This PR will provide some documentation updates regarding the new Open Government Data functionalities 

- [x] New pkgdown articles in `vignettes/` 
- [x] Update existing articles in `vignettes/`
- [x] Overhaul documentation in `man/`
- [x] Refactor exports and other parts of the NAMESPACE

### CODE REVIEW

**Comment by GregorDeCillia** [comment]
The commits so far should cover all necessary changes to `R/` except some functions for the [resources article](https://statistikat.github.io/STATcubeR/dev/articles/od_resources.html).

**Comment by GregorDeCillia** [comment]
Missing articles

- [ ] tabulation article
- [ ] caching article
- [ ] available datasets article

Additional TODOs

- [ ] update contents of `pkgdown/`
- [ ] add missing functions `od_downloads()` and `od_cache_summary()`

**Comment by GregorDeCillia** [comment]
Reminder to self: The current articles assume that you have a persistent cache set up in `~/.cache/STATcubeR/open_data`. There might be room for improvement.

**Comment by GregorDeCillia** [comment]
Github is currently experiencing some issues so I'll take the time to summarize the progress so far
This branch is now "feature complete". There are two changes that will make sure `devtools::check()` runs without errors

- [ ] remove @examples in the now internal function `sc_meta()`
- [ ] apply method consistency `print(x, ...)` to `print.od_json`

After that, I need to check if the old articles about the STATcube REST API are still working properly. They did some days ago so only minor changes are not to be expected.

**Comment by GregorDeCillia** [comment]
The current version passes `devtools::check()` with no errors, warnings or notes. Furthermore, the pkgdown site can be rendered without any issues.

### About the links

Inside of our firewall, the pkgdown docs are available at http://rstudiodevweb.statistik.local/rpkgs/dev/STATcubeR/dev/ (so much **dev**s!) and they will be updated regularly. The external docs at https://statistikat.github.io/STATcubeR/dev/ will recieve updates less frequently. When this branch is merged, the docs will be uploaded to https://statistikat.github.io/STATcubeR/

**Comment by bernhard-da** [comment]
@GregorDeCillia very nice work, all articles are very well written and very clear; just some very minor things
- https://statistikat.github.io/STATcubeR/dev/index.html -> link to setup-article does not work (is https://statistikat.github.io/STATcubeR/articles/articles/sc_key.html and should be https://statistikat.github.io/STATcubeR/dev/articles/sc_key.html
- in `https://statistikat.github.io/STATcubeR/dev/articles/sc_table.html` you could remove the part with the `raw` response as you will probably remove it in the future I guess

**Comment by GregorDeCillia** [comment]
@bernhard-da thank you. The link is now fixed in the VCS. Yes: the `sc_table class` is still a little bit weird: see the [full class documentation](http://xlwt0012/rpkgs/dev/STATcubeR/dev/reference/sc_table_class.html). It is probably a good idea not to mention that in the introduction docs.

I am not sure if `$raw` will be fully removed because there are certain parts that are "lost" when we do so, but it is certainly something for advanced users.

**Comment by GregorDeCillia** [comment]
Maybe this PR should also be used to refactor the dependencies

## Imports

* [ ] `magrittr` is not really necessary but makes for prettier code
- [x] `httr` is needed for API calls. 
- [x] `jsonlite` is necessary to parse the `httr` responses.

## Suggests

- [ ] `rmarkdown` is pretty much irrelevant since the `vignettes` are only available online
- [ ] `data.tree` provides a print method for schema endpoints but nothing else.
- [ ] `rstudioapi` allows `sc_table()$json$edit` but nothing else
- [ ] `xml2` is only used in `od_list` to do the "webscraping"
- [ ] `pillar` is just used in `.onLoad()` to register pretty printing in case the pkg is available

**Comment by GregorDeCillia** [comment]
* Version updated to 0.2.3
* gh-pages deployment at https://statistikat.github.io/STATcubeR/

**Pull request merged**
